"""
PDF report generator using ReportLab.
Produces a clean single-page PDF for a completed detection result.
"""

import os
import tempfile
from datetime import timezone

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT

from database.models import DetectionResult


# Colour palette
BRAND_DARK = colors.HexColor("#1a1a2e")
BRAND_ACCENT = colors.HexColor("#e94560")
LABEL_REAL = colors.HexColor("#27ae60")
LABEL_FAKE = colors.HexColor("#e74c3c")


def _label_colour(label: str) -> colors.Color:
    return LABEL_REAL if label == "real" else LABEL_FAKE


def generate_pdf_report(record: DetectionResult) -> str:
    """
    Generate a PDF report for a completed detection result.

    Args:
        record: DetectionResult ORM object with status == "complete"

    Returns:
        Absolute path to the generated PDF file (stored in a temp directory).
    """
    # Write to a temp file so we don't accumulate PDFs on disk
    tmp = tempfile.NamedTemporaryFile(
        suffix=".pdf", prefix=f"report_{record.id[:8]}_", delete=False
    )
    tmp.close()
    pdf_path = tmp.name

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    story = []

    # ---- Header ----
    header_style = ParagraphStyle(
        "Header",
        parent=styles["Title"],
        textColor=BRAND_DARK,
        fontSize=22,
        leading=26,
        spaceAfter=12,
        alignment=TA_CENTER,
    )
    sub_style = ParagraphStyle(
        "Sub",
        parent=styles["Normal"],
        textColor=colors.grey,
        fontSize=10,
        leading=14,
        alignment=TA_CENTER,
        spaceAfter=20,
    )

    story.append(Paragraph("Deepfake Detection Report", header_style))
    story.append(Paragraph("AI &amp; Image Authenticity Platform", sub_style))
    story.append(Spacer(1, 0.5 * cm))

    # ---- Result badge ----
    label_display = record.label.upper() if record.label else "UNKNOWN"
    confidence_pct = f"{(record.confidence or 0) * 100:.2f}%"
    label_col = _label_colour(record.label or "fake")

    badge_style = ParagraphStyle(
        "Badge",
        parent=styles["Normal"],
        textColor=label_col,
        fontSize=28,
        leading=34,
        alignment=TA_CENTER,
        spaceAfter=12,
    )
    story.append(Paragraph(f"<b>{label_display}</b>", badge_style))

    conf_style = ParagraphStyle(
        "Conf",
        parent=styles["Normal"],
        textColor=colors.darkgrey,
        fontSize=14,
        leading=18,
        alignment=TA_CENTER,
        spaceAfter=20,
    )
    story.append(Paragraph(f"Confidence: {confidence_pct}", conf_style))
    story.append(Spacer(1, 0.5 * cm))

    # ---- Details table ----
    completed = (
        record.completed_at.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        if record.completed_at
        else "—"
    )

    table_data = [
        ["Field", "Value"],
        ["Job ID", record.id],
        ["Filename", record.filename],
        ["File size", f"{record.file_size / 1024:.1f} KB"],
        ["File type", record.mime_type],
        ["Analysed at", completed],
        ["Label", label_display],
        ["Confidence", confidence_pct],
    ]

    col_widths = [5 * cm, 12 * cm]
    table = Table(table_data, colWidths=col_widths)
    table.setStyle(
        TableStyle(
            [
                # Header row
                ("BACKGROUND", (0, 0), (-1, 0), BRAND_DARK),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 11),
                ("ALIGN", (0, 0), (-1, 0), "CENTER"),
                # Data rows
                ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 1), (-1, -1), 10),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 1 * cm))

    # ---- Footer ----
    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        textColor=colors.lightgrey,
        fontSize=8,
        alignment=TA_CENTER,
    )
    story.append(
        Paragraph(
            "Generated by the Deepfake Detection Platform · For informational purposes only",
            footer_style,
        )
    )

    doc.build(story)
    return pdf_path
